// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

public class p002{
	public static int fib(){
		int first = 1;
		int second = 2;
		int next = first + second;
		int sum = 2;
		while (next < 4000000){
			first = second;
			second = next;
			if (next%2 == 0){
				sum += next;
			}
			next = first + second;
		}
		return sum;

	}

	public static void main(String args[]){
		System.out.println(fib());
	}
}